services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 40s

  api:
    build: .
    container_name: fastapi-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_PORT}:8000"
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - ./main.py:/app/main.py

volumes:
  mysql_data:
